package vinhnh.com.common;

public enum PageType {
	INDEX_HOME_PAGE,
	INDEX_PRODUCTS_PAGE,
	INDEX_DETAIL_PAGE,
	INDEX_INVOICES_PAGE,
	
	ADMIN_HOME_PAGE,
	ADMIN_PRODUCT_PAGE,
	ADMIN_LIST_PRODUCT_PAGE
}
