package vinhnh.com.common;

public enum PageType {
	INDEX_HOME_PAGE,
	INDEX_PRODUCTS_PAGE,
	INDEX_DETAIL_PAGE,
	INDEX_INVOICES_PAGE,
	INDEX_SUCCESS_PAGE,
	INDEX_STTODER_PAGE,
	INDEX_HISTORY_ORDER_PAGE,
	INDEX_CHANGE_INFORMATION_PAGE,
	INDEX_CHANGE_PASSWORD_PAGE,
	INDEX_CART_PAGE,
	INDEX_FAVORITE_PAGE,
	INDEX_PRODUCT_CATEGORI_PAGE,
	
	ADMIN_HOME_PAGE,
	ADMIN_PRODUCT_PAGE,
	ADMIN_LIST_PRODUCT_PAGE,
	ADMIN_USERS_PAGE,
	ADMIN_LIST_USER_PAGE,
	ADMIN_ROLE_USER_PAGE,
//	ORDER
	ADMIN_ALL_ORDER_PAGE,
	ADMIN_APPROVER_ORDER_PAGE,
	ADMIN_HANDLE_ORDER_PAGE,
	ADMIN_DELIVERING_ORDER_PAGE,
	ADMIN_RECEIVED_ORDER_PAGE,
	ADMIN_RECOVERY_ORDER_PAGE,
	ADMIN_DETAIL_ORDER_PAGE,
	
//	Statistical
	ADMIN_STATISTICAL_PRODUCT_PAGE,
	ADMIN_STATISTICAL_PRODUCT_SOIL_IN_MONTH_PAGE,
	ADMIN_STATISTICAL_STATUS_ORDER_PAGE
}
