CREATE DATABASE MageAnime;
go 

/*
DROP DATABASE MageAnime;
go
*/
Use MageAnime;
go

CREATE TABLE Roles(
	Id INT IDENTITY(1,1) NOT NULL,
	Position NVARCHAR(50),
	CONSTRAINT PK_Roles PRIMARY KEY (ID)
);

CREATE TABLE Users(
	Id INT IDENTITY(1,1) NOT NULL,
	Fullname NVARCHAR(100) NOT NULL,
	Birthday DATE, 
	Gender BIT NOT NULL,
	Avatar NVARCHAR(MAX),
	Phone NCHAR(15), 
	Email NVARCHAR(100) NOT NULL,
	LocaAddress NVARCHAR(255),
	Username NCHAR(30) NOT NULL,
	PassW NCHAR(30) NOT NULL,
	CreateDate Datetime,
	IdRole INT NOT NULL,
	CONSTRAINT PK_Users PRIMARY KEY (ID),
	CONSTRAINT FK_RoleUser FOREIGN KEY (IdRole) REFERENCES Roles(ID)
);

CREATE TABLE Products(
	Id INT IDENTITY(1,1),
	NameProduct  NVARCHAR(255) NOT NULL,
	Descriptions NVARCHAR(MAX) NOT NULL,
	Price MONEY NOT NULL,
	Images NVARCHAR(MAX) NOT NULL,
	CharacterName NVARCHAR(255) NOT NULL,
	MageAnime NVARCHAR(255) NOT NULL,
	Height CHAR(15) NOT NULL,
	Wight CHAR(15) NOT NULL,
	Gram CHAR(15) NOT NULL,
	CreateDate DATEtime NOT NULL,
	IdUser INT NOT NULL,
	CONSTRAINT PK_Product PRIMARY KEY (ID),
	CONSTRAINT FK_ProductUser FOREIGN KEY (IdUser) REFERENCES Users(ID)
);

CREATE TABLE Favorites(
	Id INT IDENTITY(1,1),
	DateLike DATEtime NOT NULL,
	IdUser INT NOT NULL,
	IdProduct INT NOT NULL,
	CONSTRAINT PK_Favorites PRIMARY KEY (ID),
	CONSTRAINT FK_FavoriteUser FOREIGN KEY (IdUser) REFERENCES Users(ID),
	CONSTRAINT FK_FavoriteProduct FOREIGN KEY (IdProduct) REFERENCES Products(ID)
);

CREATE TABLE Carts(
	Id INT IDENTITY(1,1),
	CreateDate Datetime NOT NULL,
	IdUser INT NOT NULL,
	IdProduct INT NOT NULL,
	CONSTRAINT PK_Carts PRIMARY KEY (ID),
	CONSTRAINT FK_CartsUser FOREIGN KEY (IdUser) REFERENCES Users(ID),
	CONSTRAINT FK_CartsProduct FOREIGN KEY (IdProduct) REFERENCES Products(ID)
);

CREATE TABLE Invoices(
	Id INT IDENTITY(1,1),
	Quantity INT NOT NULL,
	PlaceDelivery NVARCHAR(MAX) NOT NULL,
	PHONE NCHAR(15) NOT NULL,
	CreateDate DATEtime NOT NULL,
	TotalMoney MONEY NOT NULL,
	IdUser INT NOT NULL,
	IdProduct INT NOT NULL,
	CONSTRAINT PK_Invoices PRIMARY KEY (ID),
	CONSTRAINT FK_InvoicesUser FOREIGN KEY (IdUser) REFERENCES Users(ID),
	CONSTRAINT FK_InvoicesProduct FOREIGN KEY (IdProduct) REFERENCES Products(ID)
);

CREATE TABLE SttOders(
	Id INT IDENTITY(1,1),
	Statuss NVARCHAR(100) NOT NULL,
	CreateDate DATEtime NOT NULL,
	Descriptions NVARCHAR(MAX) NOT NULL,
	IdUser INT NOT NULL,
	IdInvoice INT NOT NULL,
	CONSTRAINT StatusOrders PRIMARY KEY (ID),
	CONSTRAINT FK_StatusOrdersUser FOREIGN KEY (IdUser) REFERENCES Users(ID),
	CONSTRAINT FK_StatusOrdersInvoice FOREIGN KEY (IdInvoice) REFERENCES Invoices(ID)
);